<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6-windows</TargetFramework>
    <UseWpf Condition="'$(OS)' == 'Windows_NT'">true</UseWpf>
    <AssemblyName>Embedding.Wpf</AssemblyName>
    <RootNamespace>Embedding.Wpf</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetBrowser" Version="4.2.0" />
    <PackageReference Include="DotNetBrowser.WPF" Version="4.2.0" />
  </ItemGroup>

</Project>
