<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6-windows</TargetFramework>
    <UseWindowsForms Condition="'$(OS)' == 'Windows_NT'">true</UseWindowsForms>
    <AssemblyName>Embedding.WinForms</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetBrowser" Version="4.3.0" />
    <PackageReference Include="DotNetBrowser.WinForms" Version="4.3.0" />
  </ItemGroup>

</Project>
